### ISSUE TITLE
1.12 not work paperspigot

### ISSUE THREAD

**Issue by ProDash1998** [OfficialDonut/Bitcoin#3]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [spigot.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [spigot.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [spigot.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [spigot.jar:git-Paper-1322]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
        at us._donut_.bitcoin.BitcoinMenu.createMenu(BitcoinMenu.java:85) ~[?:?]
        at us._donut_.bitcoin.BitcoinMenu.open(BitcoinMenu.java:78) ~[?:?]
        at us._donut_.bitcoin.BitcoinCommand.onCommand(BitcoinCommand.java:44) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Paper-1322]
        ... 15 more

**Comment by OfficialDonut** [comment]
Can you send the config.yml and messages.yml please. Its either something wrong there or something with player data im not sure i couldnt replicate the error

**Comment by ProDash1998** [comment]
default config
and messages

**Comment by OfficialDonut** [comment]
you are using the latest plugin version right? can you send the player data folder please
